### ISSUE TITLE
Not work :(

### ISSUE THREAD

**Issue by foshechka** [peppy/mixcloud-downloader#12]
No server found for download

**Comment by peppy** [comment]
worked for me yesterday. more detail?

**Comment by foshechka** [comment]
Try to put any link like this: https://www.mixcloud.com/globalsets/sander-van-doorn-identity-episode-315-04-dec-2015/

**Comment by kylethedude5** [comment]
Same issue.

Instead of a link to the .mp3 file, the output is "No server found for download"

**Comment by kylethedude5** [comment]
Also when I change a URL to http from https the output becomes
"An error occurred (Is the mixcloud/cloudcast url correct?)"

**Comment by penibelst** [comment]
Same here. Screenshot attached:
![mixcloud-downloader-2015-12-11](https://cloud.githubusercontent.com/assets/3617307/11752183/4de8699a-a03e-11e5-90d8-373bcac31f6d.png)

**Comment by TheLlamaLover** [comment]
Strangely other originals work other than new ones.

**Comment by GAMELASTER** [comment]
#13 fix!

**Comment by penibelst** [comment]
@GAMELASTER Great.

**Comment by peppy** [comment]
Thanks for the PR. Sorry for the delay in merging; slipped my mind!
