### ISSUE TITLE
No longer functional

### ISSUE THREAD

**Issue by TheLlamaLover** [peppy/mixcloud-downloader#15]
Seems this method no longer works. Mixcloud doesn't provide the original URL anymore.

**Comment by peppy** [comment]
Wanna give a sample URL? It's still working here (tested using [this](https://www.mixcloud.com/otographic/kenji-sekiguchi-nhato-otographic-arts-064-2015-04-07/) url).

![](https://puu.sh/n9Quw/6ceae8beb8.png)

**Comment by TheLlamaLover** [comment]
The original file for the one I had tested it on was supposed to be 266 MB about.

**Comment by peppy** [comment]
Ah, I didn't realise it was falling back to m4a. You may be right in that case.

**Comment by peppy** [comment]
FWIW `yt-dlp` works well currently.
